#!/bin/bash

# Check if all 4 parameters are provided
if [ $# -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Disable strict host key checking
SSH_OPTIONS="-o StrictHostKeyChecking=no -i $PATH_TO_SSH_KEY"

# Transfer the file using scp to the user's home directory on the server 
# shortcut: scp -> ssh + cp
scp $SSH_OPTIONS "$PATH_TO_FILE" "$USERNAME@$IP:~/" 

if [ $? -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$IP:~/"
else
    echo "Error transferring file."
fi
