#!/usr/bin/env bash

# Nginx server configuration
SERVER_CONFIG="
# redirect to my website https://dup.company
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~* \"redirect_me\") {
        rewrite ^/(.*)$ https://dup.company permanent;
    }
}"

# Write the Nginx server configuration to the default site
echo -e "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Test the Nginx configuration and handle errors
if nginx -t; then
    # If the configuration is valid, reload Nginx
    sudo nginx -s reload
    echo "Nginx configuration reloaded."
else
    # If there are errors, display an error message and exit
    echo "Nginx configuration test failed. Please check your configuration."
    exit 1
fi
