#!/usr/bin/env bash
# install and add configuration to haproxy servie
sudo usermod -aG sudo ubuntu
sudo -s
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log /dev/log local0
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

# Enable HAProxy statistics on port 8080
listen stats
    bind *:8080
    mode http
    stats enable
    stats uri /haproxy?stats
    stats auth admin:admin  # Change to a secure password

frontend http-in
    bind *:80
    mode http
    default_backend hbnb

backend hbnb
    balance roundrobin
    option httpclose
    option forwardfor
    server 364825-web-01 100.27.13.221:80 check
    server 364825-web-02 54.210.79.93:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
