#!/usr/bin/env bash
# Check if the correct number of arguments is provided
date=$(date +'%d-%m-%Y')
MYSQL_PASSWORD="$1" sudo mysqldump -uroot --all-databases >"backup.sql"
tar -czvf "$date.tar.gz" "backup.sql"
rm "backup.sql"
