#!/usr/bin/bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
mv /var/www/html/index.nginx-debian.html /var/www/html/index.html
sudo service nginx restart