#!/usr/bin/env bash
# This script edits the nginx config file to change the listening port from 8080 to 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
