#!/usr/bin/env bash
# This script updates the Nginx config and restarts the service
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
