#!/usr/bin/env bash
# fixes the nginx config file to use port 8080 and the correct user
chmod 644 /etc/nginx/nginx.conf
sed -i -E 's/^user .*;$/user nginx;/' /etc/nginx/nginx.conf
sed -i -E 's/listen\s+.*:80;/listen 8080;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
