#!/usr/bin/env bash
# fixes the nginx config file to use port 8080 and the correct user
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apatche2
sudo -u nginx service nginx start
