#!/usr/bin/env bash
# fixes the default nginx config to use port 8080 instead of 80
chmod 644 /etc/nginx/nginx.conf
sed -i -E 's/^user .*;$/user nginx;/' /etc/nginx/nginx.conf
sed -i -E 's/listen\s+.*:80;/listen 8080;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
